### ISSUE TITLE
I'm a bit disappointed you lot haven't included a README file in the six months this repo's been up.

### ISSUE THREAD

**Issue by Windows81** [roblox-dev-forum/discourse-definitions#15]
I'm aware the plugin is not available for use at this time for bug fixes, but I've looked at this repo's commit history and couldn't find any trace of a `README.md` file anywhere.  This is disappointing because someone who may be visiting from a link or stumbling upon this from a code-search might have no idea what Rust and JavaScript are doing together.

Regards.

**Comment by Kampfkarren** [comment]
> might have no idea what Rust and JavaScript are doing together.
I'm not sure what you're talking about? There is no Rust in the codebase.

![image](https://user-images.githubusercontent.com/3190756/61588821-6d40a100-ab56-11e9-8ca2-27913ffce059.png)

**Comment by Windows81** [comment]
**I always get confused between the two!!!**

**Comment by Kampfkarren** [comment]
The repo starts with the name `discourse-`, anyone who'd work with this codebase would know you need Ruby to make a Discourse plugin along side everything else.

I don't really see this as an issue but before we release this to the general masses (outside of the dev forums) we'll have a README.

**Comment by Windows81** [comment]
When I typically look at repositories, I generally head for the README.  From what I've experienced, it's usually more ideal to include a README file, even if the project is obviously structured for a certain environment (i.e. Node.JS).
